version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: faker
    versions:
    - 5.3.1
    - 5.4.0
    - 5.5.0
    - 5.5.1
    - 5.5.2
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.3.2
    - 5.4.0
    - 5.6.0
    - 5.6.2
    - 5.6.3
    - 5.6.4
    - 5.6.5
    - 5.7.0
  - dependency-name: ember-source
    versions:
    - 3.25.0
    - 3.25.1
    - 3.25.3
  - dependency-name: "@ember/test-helpers"
    versions:
    - 2.2.0
    - 2.2.1
    - 2.2.3
  - dependency-name: ember-data
    versions:
    - 3.25.0
  - dependency-name: lint-staged
    versions:
    - 10.5.4
  - dependency-name: ember-template-lint
    versions:
    - 2.18.0
    - 2.18.1
  - dependency-name: ember-qunit
    versions:
    - 5.1.2
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.2.0
  - dependency-name: ember-cli-mirage
    versions:
    - 2.0.1
